'use client';

export default function AboutPage() {
  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white font-sans">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <a href="/dashboard" className="text-sm text-blue-400 hover:underline">&larr; Back to dashboard</a>

        <h1 className="text-3xl font-bold text-white mt-6 mb-2">How this works</h1>
        <p className="text-gray-400 mb-10">
          IODarkWatch is a demo of a maritime-surveillance concept, not an operational system. This page is the
          honest version: what the dashboard actually shows, what it&apos;s built from, and what a real deployment
          would still need.
        </p>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-3">Everything on the dashboard is simulated</h2>
          <p className="text-gray-400 leading-relaxed">
            The vessels, positions, and alerts you see are generated by <code className="text-gray-300">app/lib/vessels.ts</code>,
            not a live AIS feed or satellite pipeline. Positions are placed in real Indian Ocean corridors
            (Arabian Sea, Bay of Bengal, Gulf of Aden, the Malacca Strait approach) so the scenarios read
            plausibly, but nothing here is a real vessel or a real detection.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-3">Three alert types, three different meanings</h2>
          <div className="space-y-4">
            <div className="bg-[#1a1a1a] border border-[#333] rounded-xl p-5">
              <div className="flex items-center space-x-2 mb-2">
                <div className="w-2 h-2 rounded-full bg-red-500" />
                <h3 className="font-medium text-white">Dark Vessel</h3>
              </div>
              <p className="text-sm text-gray-400">
                A vessel physically detected by satellite imagery with no AIS broadcast matching its position —
                the strongest signal that a vessel is deliberately untracked. This is the concept the project is
                named for, and it&apos;s the one piece with no working implementation anywhere in this repo: there&apos;s
                no live satellite feed and no real AIS-to-satellite correlation logic. The dashboard represents it
                with fabricated scenarios only.
              </p>
            </div>
            <div className="bg-[#1a1a1a] border border-[#333] rounded-xl p-5">
              <div className="flex items-center space-x-2 mb-2">
                <div className="w-2 h-2 rounded-full bg-orange-500" />
                <h3 className="font-medium text-white">AIS Gap</h3>
              </div>
              <p className="text-sm text-gray-400">
                A previously active vessel whose own transponder has gone silent for 12+ hours. This only needs a
                vessel&apos;s own AIS history, no satellite data — it&apos;s the cheapest signal to compute for real.
              </p>
            </div>
            <div className="bg-[#1a1a1a] border border-[#333] rounded-xl p-5">
              <div className="flex items-center space-x-2 mb-2">
                <div className="w-2 h-2 rounded-full bg-yellow-500" />
                <h3 className="font-medium text-white">Spoofing Signature</h3>
              </div>
              <p className="text-sm text-gray-400">
                A vessel whose AIS-reported speed and position don&apos;t add up — e.g. speed reported as 0 while
                position keeps changing. Also computable from AIS alone.
              </p>
            </div>
          </div>
          <p className="text-sm text-gray-500 mt-4">
            See <a href="https://github.com/S1rlvk/IODarkWatch/blob/main/CONTEXT.md" className="text-blue-400 hover:underline">CONTEXT.md</a> for
            the full glossary and <a href="https://github.com/S1rlvk/IODarkWatch/blob/main/docs/adr/0001-dark-vessel-terminology.md" className="text-blue-400 hover:underline">the ADR</a> for
            why these are kept separate instead of one &quot;dark vessel&quot; flag.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-3">The ML pipeline is real, and it doesn&apos;t work yet</h2>
          <p className="text-gray-400 leading-relaxed mb-3">
            <code className="text-gray-300">ml_pipeline/</code> contains a genuine attempt at the Dark Vessel side
            of this: a real Sentinel-1 SAR image was fetched, and a YOLOv8x model was trained to find vessels in
            it. It&apos;s not wired into this app.
          </p>
          <p className="text-gray-400 leading-relaxed">
            The honest numbers, straight from that run&apos;s own <code className="text-gray-300">deployment_config.json</code>:
            trained on 25 images (20 train / 5 validation), <code className="text-gray-300">mAP50: 0.0</code>,
            deployment marked <code className="text-gray-300">not ready</code>. It&apos;s a working end-to-end pipeline
            (fetch &rarr; train &rarr; deployment config &rarr; inference server) attached to a model that isn&apos;t
            accurate enough to detect anything yet.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">Want the full story?</h2>
          <p className="text-gray-400 leading-relaxed">
            The deeper write-up — architecture, the terminology decision, what the ML run actually produced, and
            what a real production version would need — is in{' '}
            <a
              href="https://github.com/S1rlvk/IODarkWatch/blob/main/docs/CASE-STUDY.md"
              className="text-blue-400 hover:underline"
            >
              docs/CASE-STUDY.md
            </a>.
          </p>
        </section>
      </div>
    </div>
  );
}
